### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jro619** [jeremysiegel/jeremysiegel.github.io#1]
### Summary

Circumcised mispelled

### Steps to Reproduce

- Navigate to "Male External"
- Click on "Foreskin"
- Notice that Circumcised is spelled "Circumcsed"

![image](https://user-images.githubusercontent.com/5823601/115132805-2dc41480-9fc9-11eb-84f8-8c4ee7bdd0d9.png)

### Acceptance Criteria
- "Circumcised" should be spelled correctly on a Puberty App

Don't hesitate to reach out with any additional questions.

**Comment by jeremysiegel** [comment]
Thanks for the heads up, definitely don't want to make a mistake with circumcision.
